### PR TITLE
Implement extensions

### LINKED ISSUE #24: Implement extensions
Implement #23.

### PR DESCRIPTION
**Pull request by alexdevteam**
Implements extensions (datapaths) into the engine. Closes #24.

### CODE REVIEW

**Comment by karnkaul** [comment]
I can't launch because `addBaseContent()` crashes due to, I'm guessing, searching iteratively from the working directory instead of the executable directory (which would need to be passed in from `main`); that causes `fs::recursive_directory_iterator` to throw on some edge cases, probably invalid symlinks.

Getting past that by passing the exe path, YAML crashes on interaction with the debug standard library runtime, which is basically due to the fact that it's being built with the wrong runtime, ie, the MSVC equivalent of mixing `/MDd` with `/MD`. The fix is to ensure _all_ binaries that use the standard library - including third party libraries: `ecs` and `yaml` - have `_GLIBCXX_DEBUG` defined.

On fixing that our own API throws a runtime error of `extra_content.yml` not found, so now I'm stuck. 😛

Pls fix! Also, why has CMakeLists.txt entirely changed its formatting?

@alexdevteam

**Comment by NotAPenguin0** [comment]
`addBaseContent` should no longer be needed with the current system. One `startup.yml` should be enough to launch the entire system.

**Comment by alexdevteam** [comment]
> `addBaseContent` should no longer be needed with the current system.

addBaseContent doesn't exist anymore. :P Look at the header source.

**Comment by alexdevteam** [comment]
> Also, why has CMakeLists.txt entirely changed its formatting?
CLion autoformatting. Since clang-format has no effect on it CLion just applies default formatting. We should probably accept a standard formatting style for CMake as well to prevent this.

**Review by NotAPenguin0 — APPROVED** [review]

**Review by karnkaul — APPROVED** [review]

**Pull request merged**
